### ISSUE TITLE
下拉菜单控件的问题

### ISSUE THREAD

**Issue by flashlab** [rxdrag/rxeditor#88]
下拉菜单的标题不显示，不知道是不是设置的问题

**Comment by rxdrag** [comment]
修改按钮时产生的一个bug，我修正一下

**Comment by rxdrag** [comment]
> 下拉菜单的标题不显示，不知道是不是设置的问题

修正完成了，但是确认框按钮文字跟tooltip文字颜色还有些问题，这个需要抽时间加个无样式文本组件来解决
