### ISSUE TITLE
如何实现请求数据源管理？

### ISSUE THREAD

**Issue by wulucxy** [rxdrag/rxeditor#90]
类似于阿里 lowcode-engine 的变量绑定能力

<img width="698" alt="image" src="https://user-images.githubusercontent.com/5326403/223113938-5a0a69d0-2b5a-40ca-b904-78af33f6dd9f.png">

**Comment by rxdrag** [comment]
fieldy模块管理页面的数据模型，绑定的话直接给schema的x-field字段赋值就可以。比如示例中列表内数据的绑定：
![image](https://user-images.githubusercontent.com/18096128/223305382-4fc389c9-0a39-48c0-8e82-6c074df49ea4.png)
这个绑定输入可以根据需要换成下拉选择，直接操作的是schema的x-field字段，渲染引擎会把这个信息解析成数据树，在逻辑编排时可以使用。
整个列表的数据，可以通过逻辑编排绑定：
![image](https://user-images.githubusercontent.com/18096128/223305762-385f9bef-9875-4266-a3b8-b6b7a589dd8d.png)
在初始化事件中，获取数据，然后赋值给组件的datasource：
![image](https://user-images.githubusercontent.com/18096128/223305906-656a23b1-2c86-4483-b2c2-8026304cde14.png)
示例只是模拟，你可以做自己的逻辑组件，实现类似useSwr的效果

**Comment by rxdrag** [comment]
要是没有其他问题，我关issue了哈
